export const {
  VITE_CLIENT_ID,
  VITE_CLIENT_SECRET,
  VITE_LIKED_SONGS_TOKEN,
  VITE_REDIRECT_URI,
  VITE_RESPONSE_TYPE,
  VITE_SPOTIFY_AUTH,
  VITE_SPOTIFY_BASE_URL,
  VITE_SPOTIFY_TOKEN
} = import.meta.env
