export const {
  VITE_CLIENT_ID,
  VITE_CLIENT_SECRET,
  VITE_JSONPLACEHOLDER_BASE_URL,
  VITE_REDIRECT_URI,
  VITE_RESPONSE_TYPE,
  VITE_SPOTIFY_AUTH,
  VITE_SPOTIFY_BASE_URL,
  VITE_UNAVATAR_BASE_URL
} = import.meta.env
